version: '3.7'

services:
    users:
        build:
            context: ./services/users
            dockerfile: Dockerfile-prod

        #volumes used to mount the code into the container which
        #helps when developing by updating the container whenever
        #a change is made to the source code
#        volumes:
#            - './services/users:/usr/src/app'
        expose:
            - 5000
        environment:
            - FLASK_ENV=production
            - APP_SETTINGS=project.config.DevelopmentConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
            - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
#            - COMPOSE_CONVERT_WINDOWS_PATHS=1
        depends_on:
            - users-db

    users-db:
        build:
            context: ./services/users/project/db
            dockerfile: Dockerfile
        espose:
            - 5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    nginx:
        build:
            context: ./services/nginx
            dockerfile: Dockerfile-prod
            restart: always
            ports:
                - 80:80
            depends_on:
                - users
