FROM python:3.7.2-alpine
LABEL maintainer="Kristopher Kinzler"

#i'm not sure what these dependencies are being
#installed for and why they weren't needed before
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

WORKDIR /usr/src/app

COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod 777 /usr/src/app/entrypoint-prod.sh

COPY . /usr/src/app

CMD ["/usr/src/app/entrypoint-prod.sh"]
